/**
 * Domain types shared by the bridge, the logic modules and the components.
 *
 * These mirror the Rust command contract. Fields the Rust side does not send
 * yet are optional rather than required, so a leaner payload degrades to a
 * quieter UI instead of a crash.
 */

export type Modality = "image" | "video" | "audio" | "3d";

export interface Route {
  id: string;
  provider: string;
  slug: string;
  /** Why this route is ordered where it is, from the registry. */
  note?: string;
  /** Can this route actually run — key present *and* a client implemented. */
  available?: boolean;
  /** Why not, when it cannot. */
  unavailableReason?: string;
}

/**
 * What one model can actually be asked for, from its own declared flags.
 *
 * Each axis carries two facts, and the distinction is the whole point:
 * `supports*` says the control exists at all, the list says which values.
 * A supported axis with an empty list means the model takes a *free* value —
 * 28 of 32 video models declare duration as a plain integer — and the UI must
 * offer an input rather than invent choices. Conflating the two is what made
 * the chip row report the same three durations for all 68 models.
 */
export interface ModelCapabilities {
  supportsDuration: boolean;
  /** Seconds. Empty when free-form or absent — check `supportsDuration`. */
  durations: number[];
  defaultDuration?: number | null;
  supportsResolution: boolean;
  resolutions: string[];
  defaultResolution?: string | null;
  supportsAspect: boolean;
  aspects: string[];
  defaultAspect?: string | null;
  /** The model can *produce* sound, not merely accept it as input. */
  audio: boolean;
  /** Cross-field rules the flag table cannot express, verbatim from the spec. */
  constraints: string[];
  /**
   * Media roles this model cannot take on the selected route, by wire name.
   *
   * Empty until a route is chosen. Drives the greyed-out slots: the use case
   * says the job has an End Frame, this says whether the model has anywhere
   * to put it.
   */
  unsupportedRoles: string[];
}

export interface Model {
  id: string;
  displayName: string;
  modality: Modality;
  routes: Route[];
  isLaunch: boolean;
  /** One-line description in the model picker. */
  subtitle?: string;
  /**
   * Always present from the shell. Optional only so mock data and a
   * shell-less browser session still typecheck; `capabilitiesFor` treats an
   * absent value as "unknown", never as a set of plausible defaults.
   */
  capabilities?: ModelCapabilities;
}

export interface PresetVariant {
  modelId: string;
  /** Preview media generated by us. Never a third-party CDN URL. */
  previewUrl?: string;
}

export interface PresetFamily {
  id: string;
  displayName: string;
  category: string;
  tags: string[];
  description: string;
  /** Absent means the family is model-agnostic and compiles for anything. */
  variants?: PresetVariant[];
}


export interface CostEstimate {
  usd: number;
  /** Human-readable derivation, e.g. "8s x 720p at $0.30/s". */
  basis: string;
  minimumApplied?: boolean;
}

/**
 * The provider status machine, normalized by Rust.
 *
 * Kept open (`string & {}`) because providers keep inventing intermediate
 * stages; an unrecognized stage must render as generic activity, not blow up
 * an exhaustive switch.
 */
export type JobStatus =
  | "waiting"
  | "queued"
  | "in_progress"
  | "completed"
  | "failed"
  | "canceled"
  | "nsfw"
  // eslint-disable-next-line @typescript-eslint/ban-types
  | (string & {});

/**
 * Deliberately the Rust `MediaRole` serde names, not friendlier UI ones.
 * A translation table between the two would be one more thing to drift, and
 * the failure mode — a role that binds to the wrong wire flag — is silent.
 */
export type MediaRole =
  | "start"
  | "end"
  | "reference"
  | "video"
  | "video_reference"
  | "audio"
  | "audio_reference";

/** Mirrors `hickeyfield_core::MediaSource`, which is `#[serde(tag = "kind")]`. */
export type MediaSource =
  | { kind: "local"; path: string }
  | { kind: "url"; url: string }
  | { kind: "data_uri"; data: string };

export interface MediaRef {
  role: MediaRole;
  source: MediaSource;
  /**
   * Display only, never sent. A `blob:` URL for instant rendering; Rust
   * ignores unknown fields, so this rides along harmlessly.
   */
  preview?: string;
  /** Local file name, shown in the slot and the reference strip tooltip. */
  name?: string;
}

export interface JobResult {
  /**
   * The provider's URL. **Signed and expiring** — fal's lapse, and Higgsfield
   * deletes results after 7 days — so this is the fallback, not the source of
   * truth. Prefer `localPath`.
   */
  url: string;
  /**
   * Absolute path in the user's library, once the bytes are on disk. This is
   * what "your results stay on this machine" actually means; rendering `url`
   * after the signature lapses leaves a blank card next to a perfectly good
   * file.
   */
  localPath?: string | null;
  kind: "image" | "video" | "audio";
  width?: number;
  height?: number;
  /** Still frame for a video result, used before the clip is playable. */
  poster?: string;
}

export interface GenSettings {
  duration: number;
  resolution: string;
  aspect: string;
  audio: boolean;
  enhance: boolean;
  seed?: number | null;
  steps?: number | null;
}

export interface JobSet {
  id: string;
  modelId: string;
  status: JobStatus;
  prompt: string;
  enhancedPrompt?: string | null;
  createdAt: string;
  results: JobResult[];
  route: Route;
  /** null means the provider published no price for this call. Not zero. */
  estimatedUsd: number | null;
  actualUsd?: number | null;
  presetId?: string | null;
  presetName?: string | null;
  settings?: GenSettings;
  media?: MediaRef[];
  /** Which enhancer rewrote the prompt. Higgsfield does not expose this. */
  enhancerVersion?: string | null;
  /**
   * Why the prompt was not rewritten, when it was not. Rendered next to the
   * Enhance toggle so "enhance was on and nothing changed" is never silent.
   */
  enhanceNote?: string | null;
  /**
   * Things that happened which you should know but which did not fail the
   * job — most often a setting this endpoint has no field for. Distinct from
   * `failReason` (the job died) and `enhanceNote` (about the rewriter).
   */
  advisories?: string[];
  failReason?: string | null;
}

/**
 * The user's explicit enhancer choice. `null`/omitted means "decide for me":
 * the shell auto-detects. `backend` is `"ollama"` or `"openai"`; `model` is the
 * installed Ollama tag or the hosted model id (required for both).
 */
export interface RewriterChoice {
  backend: string;
  model?: string;
}

export interface SubmitInput {
  modelId: string;
  routeId: string;
  prompt: string;
  presetId: string | null;
  settings: GenSettings;
  media: MediaRef[];
  /** null means auto — the shell picks from what is actually reachable. */
  rewriter?: RewriterChoice | null;
}

/**
 * A use case slug from Rust — `text-to-video`, `edit-video`, …
 *
 * Replaces the old `create | edit | motion` triple, which named Higgsfield's
 * surfaces rather than jobs and filtered nothing: every model was offered under
 * every tab, so you could sit in "Edit Video" with a clip attached, pick a
 * text-only model, and only find out after submitting.
 */
export type WorkspaceTab = string;

export interface UseCase {
  slug: string;
  label: string;
  blurb: string;
  /** `[role, required]`. A required slot the job cannot run without. */
  slots: [string, boolean][];
  requiresMedia: boolean;
}
