#!/usr/bin/env python3
"""Provenance lint. Two independent checks, both CI gates.

1. No third-party CDN hostnames anywhere in the repo. Every preview, thumbnail
   and sample must be generated by us. Hotlinking their media is a copyright
   problem, and "just temporarily during development" is exactly how such a
   reference survives to release.

2. No verbatim third-party product copy in strings we ship. Short functional
   labels ("Generate", "Aspect ratio") are unavoidable and uncopyrightable;
   anything longer must be written by us. Checked against one-way shingle
   digests, so the reference text itself is never stored in this repo — see
   build-provenance-index.py.

Usage:
    scripts/lint-provenance.py            # check
    scripts/lint-provenance.py --verbose  # show every match
"""

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

FORBIDDEN_HOSTS = [
    "cdn.higgsfield.ai",
    "static.higgsfield.ai",
    "images.higgs.ai",
    "assets.higgsfield.ai",
    "fnf-api-gw.higgsfield.ai",
    # Their output/preview CloudFront distributions.
    "dqv0cqkoy5oj7.cloudfront.net",
    "d2ol7oe51mr4n9.cloudfront.net",
    "d8j0ntlcm91z4.cloudfront.net",
    "du4zrvwy3vtek.cloudfront.net",
    "d1xarpci4ikg0w.cloudfront.net",
]

# platform.higgsfield.ai is deliberately allowed: it is a provider the user may
# opt into with their own key, not a media source we would be hotlinking.
ALLOWED_HOSTS = ["platform.higgsfield.ai", "docs.higgsfield.ai"]

SCAN_SUFFIXES = {".rs", ".ts", ".tsx", ".js", ".jsx", ".css", ".html", ".json", ".md", ".sh", ".yml", ".yaml"}

SKIP_DIRS = {
    ".git", "target", "node_modules", "dist", "provenance",
    # The vendored MIT spec is a licensed third-party file quoted as-is.
    "vendor",
    # FORGE project-management scaffolding (planning + phase evidence). Committed,
    # but never bundled into the shipped app, and evidence docs legitimately quote
    # the very strings under discussion. Same class as `provenance`/`vendor`.
    # See .forge/PROVENANCE-SCOPE.md.
    ".forge",
}

# Mirrors build-provenance-index.py. Keep in sync.
SHINGLE = 5
MIN_WORDS = 8
DIGEST_HEX = 12
# A string must share this many shingles with the corpus before we call it
# lifted. One or two can happen by chance in ordinary product English.
MATCH_THRESHOLD = 3

_WORD = re.compile(r"[a-z0-9]+")
# String and template literals in source, plus markdown prose is scanned whole.
_LITERAL = re.compile(r'"((?:[^"\\\n]|\\.){12,})"' r"|'((?:[^'\\\n]|\\.){12,})'")


def normalize(text: str) -> list[str]:
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"\{\{?[^}]*\}?\}", " ", text)
    return _WORD.findall(text.lower())


def shingles(words: list[str]) -> set[str]:
    if len(words) < SHINGLE:
        return set()
    return {
        hashlib.sha256(" ".join(words[i : i + SHINGLE]).encode()).hexdigest()[:DIGEST_HEX]
        for i in range(len(words) - SHINGLE + 1)
    }


def load_index() -> set[str]:
    p = REPO / "provenance" / "i18n-shingles.txt"
    if not p.exists():
        return set()
    return {
        line.strip()
        for line in p.read_text().splitlines()
        if line.strip() and not line.startswith("#")
    }


def scan_files():
    for path in REPO.rglob("*"):
        if not path.is_file() or path.suffix not in SCAN_SUFFIXES:
            continue
        if any(part in SKIP_DIRS for part in path.relative_to(REPO).parts):
            continue
        # The scripts implementing the lint necessarily name the things they ban.
        if path.name in {"lint-provenance.py", "build-provenance-index.py"}:
            continue
        yield path


def check_hosts(verbose: bool) -> list[str]:
    problems = []
    for path in scan_files():
        try:
            text = path.read_text(errors="ignore")
        except OSError:
            continue
        for lineno, line in enumerate(text.splitlines(), 1):
            for host in FORBIDDEN_HOSTS:
                if host in line and not any(a in line for a in ALLOWED_HOSTS):
                    rel = path.relative_to(REPO)
                    problems.append(f"{rel}:{lineno}: references {host}")
    return problems


def check_copy(index: set[str], verbose: bool) -> list[str]:
    if not index:
        print(
            "  note: no provenance index found — run build-provenance-index.py "
            "to enable the copy check",
            file=sys.stderr,
        )
        return []

    problems = []
    for path in scan_files():
        try:
            text = path.read_text(errors="ignore")
        except OSError:
            continue

        if path.suffix == ".md":
            candidates = [(i, ln) for i, ln in enumerate(text.splitlines(), 1) if len(ln.split()) >= MIN_WORDS]
        else:
            candidates = []
            for lineno, line in enumerate(text.splitlines(), 1):
                for m in _LITERAL.finditer(line):
                    candidates.append((lineno, m.group(1) or m.group(2)))

        for lineno, raw in candidates:
            words = normalize(raw)
            if len(words) < MIN_WORDS:
                continue
            hits = shingles(words) & index
            if len(hits) >= MATCH_THRESHOLD:
                rel = path.relative_to(REPO)
                snippet = " ".join(raw.split())[:70]
                problems.append(
                    f"{rel}:{lineno}: {len(hits)} shingles match reference copy — “{snippet}…”"
                )
    return problems


def main() -> int:
    verbose = "--verbose" in sys.argv
    failures = 0

    print("CDN hostnames")
    host_problems = check_hosts(verbose)
    if host_problems:
        failures += len(host_problems)
        for p in host_problems:
            print(f"  FAIL  {p}")
    else:
        print("  PASS  no third-party media hosts referenced")

    print("Copy provenance")
    index = load_index()
    copy_problems = check_copy(index, verbose)
    if copy_problems:
        failures += len(copy_problems)
        for p in copy_problems:
            print(f"  FAIL  {p}")
    else:
        n = len(index)
        print(f"  PASS  no shipped string matches the reference corpus ({n} shingles indexed)")

    if failures:
        print(f"\n{failures} provenance problem(s). Author your own wording, or")
        print("generate your own asset — do not relax the threshold.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
